name: Tests

on:
  push:
    branches: ["main", "develop", "community-edition"]
  pull_request:
    branches: ["main", "develop", "community-edition"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest-m

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run halo2-base tests
        working-directory: "halo2-base"
        run: |
          cargo test
      - name: Run halo2-ecc tests MockProver
        working-directory: "halo2-ecc"
        run: |
          cargo test -- --skip bench
      - name: Run halo2-ecc tests (real prover)
        working-directory: "halo2-ecc"
        run: |
          cargo test --release -- bench_secp256k1_ecdsa
          cargo test --release -- bench_ec_add
          mv configs/bn254/bench_fixed_msm.t.config configs/bn254/bench_fixed_msm.config
          cargo test --release -- bench_fixed_base_msm
          mv configs/bn254/bench_msm.t.config configs/bn254/bench_msm.config
          cargo test --release -- bench_msm
          mv configs/bn254/bench_pairing.t.config configs/bn254/bench_pairing.config
          cargo test --release -- bench_pairing
      - name: Run zkevm-keccak tests
        working-directory: "hashes/zkevm-keccak"
        run: |
          cargo test
