name: Tests

on:
  push:
    branches: ["main", "develop", "community-edition"]
  pull_request:
    branches: ["main", "develop", "community-edition"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest-m

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run halo2-base tests
        working-directory: "halo2-base"
        run: |
          cargo test -- --test-threads=1
      - name: Run halo2-ecc tests
        working-directory: "halo2-ecc"
        run: |
          cargo test -- --nocapture
